# Load & Initial Inspection

In [10]:
import pandas as pd
import numpy as np

df= pd.read_csv(r"C:\Users\user\Downloads\messy_healthcare_dataset_150k.csv")

print(df.shape)

df.info() 

df.head()

(158000, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158000 entries, 0 to 157999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Patient_ID      153361 non-null  object
 1   Age             142188 non-null  object
 2   Gender          129330 non-null  object
 3   Height_cm       138202 non-null  float64
 4   Weight_kg       138140 non-null  float64
 5   BMI             112608 non-null  float64
 6   Blood_Pressure  126028 non-null  object
 7   Heart_Rate      135631 non-null  float64
 8   Cholesterol     135397 non-null  object
 9   Diabetes        126585 non-null  object
 10  Smoking_Status  123135 non-null  object
 11  Admission_Date  105692 non-null  object
 12  Discharge_Date  105454 non-null  object
 13  Hospital        118216 non-null  object
 14  Billing_Amount  135472 non-null  float64
dtypes: float64(5), object(10)
memory usage: 18.1+ MB

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Blood_Pressure,Heart_Rate,Cholesterol,Diabetes,Smoking_Status,Admission_Date,Discharge_Date,Hospital,Billing_Amount
0,PAT1000000,75,MALE,180.0,NaN,18.5,130/85,NaN,150,No,Unknown,15-11-2020,02/27/2020,NaN,50000.0
1,NaN,65,F,190.0,85.0,NaN,120/80,250.0,high,NaN,Unknown,29-11-2022,NaN,Metro Medical Center,5000.0
2,PAT1000002,35,F,50.0,65.0,22.3,110/70,-5.0,220,NaN,smoker,16-11-2022,"July 09, 2022",CITY HOSPITAL,20000.0
3,PAT1000003,-10,NaN,160.0,95.0,18.5,80/40,72.0,NaN,yes,Smoker,NaN,14-07-2021,City Hospital,NaN
4,PAT1000004,unknown,F,300.0,75.0,22.3,200/150,95.0,220,NaN,NaN,2001-09-29,NaN,city hospital,NaN

# Checking nulls, percentage of nulls, empty strings, whitespace, trim, dtypes, date format check, etc.

# STEP 1: (a) Check for True Null Values (NaN / None)

In [11]:
df.isnull().sum()

Patient_ID         4639
Age               15812
Gender            28670
Height_cm         19798
Weight_kg         19860
BMI               45392
Blood_Pressure    31972
Heart_Rate        22369
Cholesterol       22603
Diabetes          31415
Smoking_Status    34865
Admission_Date    52308
Discharge_Date    52546
Hospital          39784
Billing_Amount    22528
dtype: int64

In [12]:
# Percentage of nulls

(df.isnull().sum() / len(df)) * 100

Patient_ID         2.936076
Age               10.007595
Gender            18.145570
Height_cm         12.530380
Weight_kg         12.569620
BMI               28.729114
Blood_Pressure    20.235443
Heart_Rate        14.157595
Cholesterol       14.305696
Diabetes          19.882911
Smoking_Status    22.066456
Admission_Date    33.106329
Discharge_Date    33.256962
Hospital          25.179747
Billing_Amount    14.258228
dtype: float64

In [13]:
df.isnull().mean().sort_values(ascending=False)

Discharge_Date    0.332570
Admission_Date    0.331063
BMI               0.287291
Hospital          0.251797
Smoking_Status    0.220665
Blood_Pressure    0.202354
Diabetes          0.198829
Gender            0.181456
Cholesterol       0.143057
Billing_Amount    0.142582
Heart_Rate        0.141576
Weight_kg         0.125696
Height_cm         0.125304
Age               0.100076
Patient_ID        0.029361
dtype: float64

# Step 1: (b) check for empty strings

In [14]:
(df == "").sum()

Patient_ID        0
Age               0
Gender            0
Height_cm         0
Weight_kg         0
BMI               0
Blood_Pressure    0
Heart_Rate        0
Cholesterol       0
Diabetes          0
Smoking_Status    0
Admission_Date    0
Discharge_Date    0
Hospital          0
Billing_Amount    0
dtype: int64

## No Empty strings found

# Step 1: (c) Check for Whitespaces (Leading/Trailing Spaces)

In [16]:
# Detect leading/trailing spaces:

df["Hospital"].str.startswith(" ").sum()
df["Hospital"].str.endswith(" ").sum()

39402

In [17]:
 # Detect values that change after stripping:

(df["Hospital"] != df["Hospital"].str.strip()).sum()

99161

# Step 1: (d) Check for "unknown", "invalid", etc.(inspecting unique values, before replacing)

In [18]:
df["Gender"].value_counts(dropna=False)

Gender
NaN        28670
female     14620
FEMALE     14576
unknown    14480
Female     14442
male       14420
Male       14334
F          14246
MALE       14115
M          14097
Name: count, dtype: int64

In [19]:
# Case sensitive values check

df["Gender"].str.lower().value_counts(dropna=False)

Gender
male       42869
female     29062
NaN        28670
female     14576
unknown    14480
f          14246
m          14097
Name: count, dtype: int64

# Step 1: (e) Detect Mixed Data Types

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158000 entries, 0 to 157999
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Patient_ID      153361 non-null  object
 1   Age             142188 non-null  object
 2   Gender          129330 non-null  object
 3   Height_cm       138202 non-null  float64
 4   Weight_kg       138140 non-null  float64
 5   BMI             112608 non-null  float64
 6   Blood_Pressure  126028 non-null  object
 7   Heart_Rate      135631 non-null  float64
 8   Cholesterol     135397 non-null  object
 9   Diabetes        126585 non-null  object
 10  Smoking_Status  123135 non-null  object
 11  Admission_Date  105692 non-null  object
 12  Discharge_Date  105454 non-null  object
 13  Hospital        118216 non-null  object
 14  Billing_Amount  135472 non-null  float64
dtypes: float64(5), object(10)
memory usage: 18.1+ MB

In [ ]:
# Detect non-numeric values in numeric column:

df[~df["Age"].astype(str).str.isnumeric()]

,Patient_ID,Age,Gender,Height_cm,Weight_kg,BMI,Blood_Pressure,Heart_Rate,Cholesterol,Diabetes,Smoking_Status,Admission_Date,Discharge_Date,Hospital,Billing_Amount
3,PAT1000003,-10,NaN,160.0,95.0,18.5,80/40,72.0,NaN,yes,Smoker,NaN,14-07-2021,City Hospital,NaN
4,PAT1000004,unknown,F,300.0,75.0,22.3,200/150,95.0,220,NaN,NaN,2001-09-29,NaN,city hospital,NaN
8,PAT1000008,-10,female,170.0,-20.0,NaN,300/200,85.0,180,no,smoker,NaN,2023-11-18,NaN,-1000.0
10,PAT1000010,NaN,Male,NaN,95.0,18.5,110/70,60.0,150,yes,NaN,NaN,NaN,city hospital,NaN
13,PAT1000013,NaN,female,170.0,NaN,27.8,invalid,72.0,220,NaN,NaN,NaN,NaN,NaN,999999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157989,PAT1127721,-10,female,170.0,75.0,31.2,NaN,NaN,220,N,FORMER,NaN,04/09/2021,Metro Medical Center,NaN
157994,PAT1033702,NaN,F,50.0,500.0,18.5,invalid,72.0,150,No,smoker,NaN,11/04/2024,NaN,999999.0
157996,PAT1044876,-10,FEMALE,170.0,50.0,27.8,130/85,60.0,-50,N,Smoker,31-07-2025,NaN,city hospital,20000.0
157997,PAT1110495,unknown,Female,160.0,65.0,18.5,80/40,72.0,150,NaN,smoker,02/09/2025,1996-06-28,GENERAL HOSPITAL,999999.0
157998,PAT1025466,NaN,male,190.0,-20.0,NaN,invalid,250.0,-50,Yes,Smoker,30-06-2024,NaN,NaN,-1000.0

In [ ]:

pd.to_numeric(df["Age"], errors="coerce").isna().sum()

31428

## 31428 values will break during conversion

# Step 1: (f) Detect Hidden Whitespace Everywhere (All Columns)

In [23]:
for col in df.select_dtypes(include="object"):
    count = (df[col] != df[col].str.strip()).sum()
    print(col, ":", count)

Patient_ID : 4639
Age : 15812
Gender : 43246
Blood_Pressure : 31972
Cholesterol : 22603
Diabetes : 62982
Smoking_Status : 52585
Admission_Date : 52308
Discharge_Date : 52546
Hospital : 99161

# Step 1: (g) Detect Suspicious Categorical Variations

In [24]:
df["Gender"].str.lower().unique()

array(['male', 'f', nan, 'female', 'female ', 'm', 'unknown'],
      dtype=object)

In [40]:
df["Smoking_Status"].str.lower().unique()

array(['unknown', 'smoker', nan, 'non smoker', 'former ', 'former',
       'non-smoker'], dtype=object)

In [41]:
df["Hospital"].str.lower().unique()

array([nan, 'metro medical center', 'city hospital', 'city hospital ',
       'general hospital ', ' general hospital'], dtype=object)

# Step 1: (h) Check Date Format Issues

In [37]:
df["Admission_Date"].unique()[:10]

array([0], dtype=int64)

In [38]:
df["Admission_Date"].unique()[:20]

array([0], dtype=int64)

In [33]:
## conversion impact:
df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors="coerce", dayfirst=True).isna().sum()

df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], errors="coerce", dayfirst=True).isna().sum()

# Step 1: (i) Quick Full Data Audit

In [39]:
def data_audit(df):
    summary = pd.DataFrame({
        "dtype" : df.dtypes,
        "null_count" : df.isnull().sum(),
        "null_percent" : df.isnull().mean() * 100,
        "unique_values" : df.nunique()
        })
    return summary

data_audit(df)

                  dtype  null_count  null_percent  unique_values
Patient_ID       object        4639      2.936076         145579
Age              object       15812     10.007595              9
Gender           object       28670     18.145570              9
Height_cm       float64       19798     12.530380              7
Weight_kg       float64       19860     12.569620              7
BMI             float64       45392     28.729114              5
Blood_Pressure   object       31972     20.235443              8
Heart_Rate      float64       22369     14.157595              6
Cholesterol      object       22603     14.305696              6
Diabetes         object       31415     19.882911              8
Smoking_Status   object       34865     22.066456              7
Admission_Date    int64           0      0.000000              1
Discharge_Date    int64           0      0.000000              1
Hospital         object       39784     25.179747              6
Billing_Amount  float64       22528     14.258228              6

In [53]:
import pandas as pd
import numpy as np

def audit_healthcare_data(df):
    report = {}

    # -------------------------
    # 1️⃣ Basic Info
    # -------------------------
    report["shape"] = df.shape

    # -------------------------
    # 2️⃣ Null Values
    # -------------------------
    report["null_counts"] = df.isnull().sum()
    report ["null_counts"] = (df.isnull().mean() * 100).round(2)

    # -------------------------
    # 3️⃣ Empty Strings
    # -------------------------
    empty_counts = {}
    for col in df.select_dtypes(include="object"):
        empty_counts[col] = (df[col] == "").sum()
    report["empty_strings"] = pd.Series(empty_counts)

    # -------------------------
    # 4️⃣ Whitespace Issues
    # -------------------------
    whitespace_counts = {}
    for col in df.select_dtypes(include="object"):
        whitespace_counts[col] = (
            df[col].notna() &
            (df[col] != df[col].str.strip())
        ).sum()
    report["whitespace_issues"] = pd.Series(whitespace_counts)

    # -------------------------
    # 5️⃣ Numeric Outliers (Safe Conversion)
    # -------------------------
    numeric_checks = {}

    df_temp = df.copy()

    numeric_cols = [
        "Age", "Height_cm", "Weight_kg", "Heart_Rate", "Billing_Amount"
    ]

    for col in numeric_cols:
        df_temp[col] = pd.to_numeric(df_temp[col], errors= "coerce")

    numeric_checks["age_outliers"] = df_temp[(df_temp["Age"] < 0) | (df_temp["Age"] > 120)].shape[0]
    numeric_checks["height_outliers"] = df_temp[(df_temp["Height_cm"] < 100) | (df_temp["Height_cm"] > 250)].shape[0]
    numeric_checks["weight_outliers"] = df_temp[(df_temp["Weight_kg"] < 30) | (df_temp["Weight_kg"] > 300)].shape[0]
    numeric_checks["heart_rate_outliers"] = df_temp[(df_temp["Heart_Rate"] < 30) | (df_temp["Heart_Rate"] > 220)].shape[0]
    numeric_checks["billing_negative"] = df_temp[df_temp["Billing_Amount"] < 0].shape[0]

    report["numeric_issues"] = numeric_checks
   
    # -------------------------
    # 6️⃣ Duplicate Rows
    # -------------------------
    report["duplicate_rows"] = df.duplicated().sum()

    # -------------------------
    # 7️⃣ Date Parsing Failures (Fix Warning)
    # -------------------------
    admission_parsed = pd.to_datetime(df["Admission_Date"], errors="coerce", dayfirst=True)
    discharge_parsed = pd.to_datetime(df["Discharge_Date"], errors="coerce", dayfirst=True)

    report["invalid_admission_dates"] = admission_parsed.isna().sum()
    report["invalid_discharge_dates"] = discharge_parsed.isna().sum()

    return report

In [54]:

audit_report = audit_healthcare_data(df)

for key, value in audit_report.items():
    print("\n", key)
    print(value)

 shape
(158000, 15)

 null_counts
Patient_ID         2.94
Age               10.01
Gender            18.15
Height_cm         12.53
Weight_kg         12.57
BMI               28.73
Blood_Pressure    20.24
Heart_Rate        14.16
Cholesterol       14.31
Diabetes          19.88
Smoking_Status    22.07
Admission_Date     0.00
Discharge_Date     0.00
Hospital          25.18
Billing_Amount    14.26
dtype: float64

 empty_strings
Patient_ID        0
Age               0
Gender            0
Blood_Pressure    0
Cholesterol       0
Diabetes          0
Smoking_Status    0
Hospital          0
dtype: int64

 whitespace_issues
Patient_ID            0
Age                   0
Gender            14576
Blood_Pressure        0
Cholesterol           0
Diabetes          31567
Smoking_Status    17720
Hospital          59377
dtype: int64

 numeric_issues
{'age_outliers': 31757, 'height_outliers': 39481, 'weight_outliers': 39453, 'heart_rate_outliers': 45189, 'billing_negative': 22457}

 duplicate_rows
8000

 invalid_admission_dates
0

 invalid_discharge_dates
0

# Standardize Missing Values

In [ ]:
df.replace(["", "unknown", "Unknown", "invalid", "N/A"], np.nan, inplace=True)

# Remove Duplicates

In [ ]:
df= df.drop_duplicates(subset="Patient_ID")