# Loading Dataset

In [6]:
import pandas as pd

In [7]:
# Instead of C:\Users\..., use the folder name directly
prod = pd.read_csv("raw_files/omni_products.csv")
ord = pd.read_csv("raw_files/omni_orders.csv")
cust = pd.read_csv("raw_files/omni_customers.csv")
ord_it = pd.read_csv("raw_files/omni_order_items.csv")
inv = pd.read_csv("raw_files/omni_inventory.csv")
inv_move = pd.read_csv("raw_files/omni_inventory_movements.csv")

# Understanding dataset

## Customers Table

In [8]:
cust.head()

  customer_id  customer_name       city signup_date
0   CUST00000    Arjun Mehta     Mumbai  2023-01-05
1   CUST00001    Wei Johnson    Chennai  2023-09-13
2   CUST00002     Chen Patel  Bangalore  2023-03-18
3   CUST00003  Olivia Kovacs       Pune  2023-07-12
4   CUST00004    Emma Kovacs    Chennai  2022-02-06

In [9]:
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5000 non-null   object
 1   customer_name  5000 non-null   object
 2   city           5000 non-null   object
 3   signup_date    5000 non-null   object
dtypes: object(4)
memory usage: 156.4+ KB

In [10]:
cust.isnull().sum()

customer_id      0
customer_name    0
city             0
signup_date      0
dtype: int64

In [11]:
cust['customer_id'].nunique()

5000

### Notes:
- All unique customer_ID. perfect for primary key constraint. 
- Signup date dtype is object which needs to be corrected.

In [43]:
cust['Signup_Date'] = pd.to_datetime(cust['Signup_Date'], errors='coerce')
cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Id    5000 non-null   object
 1   Customer_Name  5000 non-null   object
 2   City           5000 non-null   object
 3   Signup_Date    5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), object(3)
memory usage: 156.4+ KB

In [ ]:
cust['Signup_Date'] converted to datetime format successfully.

## Products Table

In [12]:
prod.head()

  product_id product_name     category brand    price
0  PROD00000  Dell Item_0       Sports  Dell  1888.71
1  PROD00001  Sony Item_1  Electronics  Sony  1480.04
2  PROD00002    HP Item_2  Electronics    HP   982.42
3  PROD00003  Dell Item_3  Electronics  Dell   144.96
4  PROD00004  Puma Item_4  Electronics  Puma   533.58

In [13]:
prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    800 non-null    object
 1   product_name  800 non-null    object
 2   category      800 non-null    object
 3   brand         800 non-null    object
 4   price         800 non-null    float64
dtypes: float64(1), object(4)
memory usage: 31.4+ KB

In [14]:
prod.isnull().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
dtype: int64

In [15]:
# brand consistency check - if any brand repeat.

prod['brand'].value_counts()

brand
H&M          69
Sony         67
Dell         66
Noise        62
Samsung      61
Puma         60
Decathlon    58
Nike         57
Boat         56
HP           54
Zara         52
Ikea         49
Apple        47
Adidas       42
Name: count, dtype: int64

In [16]:
prod['category'].unique()

array(['Sports', 'Electronics', 'Home', 'Fashion'], dtype=object)

# Order Table

In [17]:
ord.shape

(50000, 6)

In [45]:
ord.head(15)

      Order_Id Customer_Id Order_Date Channel  Store_Id Order_Status
0   ORD0000000   CUST03080 2024-09-06   Store  STORE038     Returned
1   ORD0000001   CUST00191 2023-06-01   Store  STORE009    Cancelled
2   ORD0000002   CUST02367 2024-04-13   Store  STORE029    Cancelled
3   ORD0000003   CUST03515 2024-09-05  Online       NaN    Delivered
4   ORD0000004   CUST00780 2024-04-16   Store  STORE004    Delivered
5   ORD0000005   CUST00613 2024-08-23     App       NaN    Delivered
6   ORD0000006   CUST03959 2024-07-25  Online       NaN    Cancelled
7   ORD0000007   CUST03660 2023-03-06  Online       NaN     Returned
8   ORD0000008   CUST04130 2024-05-10     App       NaN    Delivered
9   ORD0000009   CUST01126 2023-10-22   Store  STORE021    Delivered
10  ORD0000010   CUST01162 2024-05-02     App       NaN      Shipped
11  ORD0000011   CUST00233 2024-06-08     App       NaN     Returned
12  ORD0000012   CUST02552 2023-09-22   Store  STORE026    Delivered
13  ORD0000013   CUST00416 2023-11-17     App       NaN    Cancelled
14  ORD0000014   CUST03787 2024-04-11     App       NaN     Returned

In [19]:
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      50000 non-null  object
 1   customer_id   50000 non-null  object
 2   order_date    50000 non-null  object
 3   channel       50000 non-null  object
 4   store_id      16715 non-null  object
 5   order_status  50000 non-null  object
dtypes: object(6)
memory usage: 2.3+ MB

In [20]:
ord.isnull().sum()

order_id            0
customer_id         0
order_date          0
channel             0
store_id        33285
order_status        0
dtype: int64

In [21]:
ord[ord.duplicated(keep=False)]

Empty DataFrame
Columns: [order_id, customer_id, order_date, channel, store_id, order_status]
Index: []

In [22]:
ord.duplicated().sum()

np.int64(0)

In [23]:
ord['channel'].value_counts()

channel
Store     16715
App       16654
Online    16631
Name: count, dtype: int64

In [24]:
ord['order_status'].value_counts()

order_status
Shipped      12599
Returned     12583
Cancelled    12562
Delivered    12256
Name: count, dtype: int64

### Notes:
- No duplicates found.
- order_date dtype is wrong.
- Nan value is present in store_id. Is likely because of non-store orders.

In [44]:
ord['Order_Date'] = pd.to_datetime(ord['Order_Date'], errors='coerce')
ord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_Id      50000 non-null  object
 1   Customer_Id   50000 non-null  object
 2   Order_Date    50000 non-null  datetime64[ns]
 3   Channel       50000 non-null  object
 4   Store_Id      16715 non-null  object
 5   Order_Status  50000 non-null  object
dtypes: datetime64[ns](1), object(5)
memory usage: 2.3+ MB

In [48]:
print(ord.columns)

Index(['Order_Id', 'Customer_Id', 'Order_Date', 'Channel', 'Store_Id',
       'Order_Status'],
      dtype='object')

In [55]:
mask = (ord['Channel'].isin(['Online', 'App'])) & (ord['Store_Id'].isna())
ord.loc[mask, 'Store_Id'] = 'ONLINE'
ord.head(15)

      Order_Id Customer_Id Order_Date Channel  Store_Id Order_Status
0   ORD0000000   CUST03080 2024-09-06   Store  STORE038     Returned
1   ORD0000001   CUST00191 2023-06-01   Store  STORE009    Cancelled
2   ORD0000002   CUST02367 2024-04-13   Store  STORE029    Cancelled
3   ORD0000003   CUST03515 2024-09-05  Online    ONLINE    Delivered
4   ORD0000004   CUST00780 2024-04-16   Store  STORE004    Delivered
5   ORD0000005   CUST00613 2024-08-23     App    ONLINE    Delivered
6   ORD0000006   CUST03959 2024-07-25  Online    ONLINE    Cancelled
7   ORD0000007   CUST03660 2023-03-06  Online    ONLINE     Returned
8   ORD0000008   CUST04130 2024-05-10     App    ONLINE    Delivered
9   ORD0000009   CUST01126 2023-10-22   Store  STORE021    Delivered
10  ORD0000010   CUST01162 2024-05-02     App    ONLINE      Shipped
11  ORD0000011   CUST00233 2024-06-08     App    ONLINE     Returned
12  ORD0000012   CUST02552 2023-09-22   Store  STORE026    Delivered
13  ORD0000013   CUST00416 2023-11-17     App    ONLINE    Cancelled
14  ORD0000014   CUST03787 2024-04-11     App    ONLINE     Returned

In [56]:
ord.isnull().sum()

Order_Id        0
Customer_Id     0
Order_Date      0
Channel         0
Store_Id        0
Order_Status    0
dtype: int64

Order_Date converted to date format. null value in Store_Id indeed null as channel for App and Online is not exist. So NaN in Store_Id filled by following rule: if NaN and Channel value is 'App' or 'Online', filled with 'ONLINE'.

## Order Items Table

In [25]:
ord_it.shape

(149958, 4)

In [26]:
ord_it.head()

   order_item_id    order_id product_id  quantity
0              1  ORD0000000  PROD00502         3
1              2  ORD0000000  PROD00666         4
2              3  ORD0000000  PROD00159         3
3              4  ORD0000000  PROD00777         1
4              5  ORD0000001  PROD00658         4

In [27]:
ord_it.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149958 entries, 0 to 149957
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_item_id  149958 non-null  int64
 1   order_id       149958 non-null  object
 2   product_id     149958 non-null  object
 3   quantity       149958 non-null  int64
dtypes: int64(2), object(2)
memory usage: 4.6+ MB

In [28]:
ord_it.isnull().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
dtype: int64

In [29]:
ord_it['order_id'].nunique()

50000

In [30]:
ord_it['quantity'].describe()

count    149958.000000
mean          2.501740
std           1.117082
min           1.000000
25%           2.000000
50%           3.000000
75%           3.000000
max           4.000000
Name: quantity, dtype: float64

### Notes:
- Only 50K order item's unique. Because of many order's in one.
- likely no invalid quantity.

### Inventory Table

In [31]:
inv.shape

(8000, 4)

In [32]:
inv.head()

  product_id warehouse_id  stock_quantity last_updated
0  PROD00000        WH000             263   2026-04-13
1  PROD00000        WH001             565   2026-04-13
2  PROD00000        WH002             284   2026-04-13
3  PROD00000        WH003              20   2026-04-13
4  PROD00000        WH004             203   2026-04-13

In [33]:
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      8000 non-null   object
 1   warehouse_id    8000 non-null   object
 2   stock_quantity  8000 non-null   int64
 3   last_updated    8000 non-null   object
dtypes: int64(1), object(3)
memory usage: 250.1+ KB

In [34]:
inv.isnull().sum()

product_id        0
warehouse_id      0
stock_quantity    0
last_updated      0
dtype: int64

In [35]:
# stock check in each warehouse
inv.groupby('warehouse_id')['stock_quantity'].sum()

warehouse_id
WH000    389718
WH001    402664
WH002    397092
WH003    406724
WH004    392143
WH005    412841
WH006    407051
WH007    392828
WH008    394715
WH009    408924
Name: stock_quantity, dtype: int64

### Notes:
- last updated dtype is wrong.

In [58]:
inv['Last_Updated'] = pd.to_datetime(inv['Last_Updated'], errors='coerce')
inv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product_Id      8000 non-null   object
 1   Warehouse_Id    8000 non-null   object
 2   Stock_Quantity  8000 non-null   int64
 3   Last_Updated    8000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 250.1+ KB

Last_Updated converted to date format.

## Inventory Movement Table

In [36]:
inv_move.shape

(100000, 5)

In [37]:
inv_move.head()

  product_id warehouse_id  change_qty   reason        date
0  PROD00578        WH005         -44  Restock  2024-04-30
1  PROD00704        WH006          82  Restock  2023-01-16
2  PROD00453        WH005           0  Restock  2023-07-20
3  PROD00702        WH007          52     Sale  2023-10-17
4  PROD00119        WH009          47     Sale  2024-10-22

In [38]:
inv_move.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   product_id    100000 non-null  object
 1   warehouse_id  100000 non-null  object
 2   change_qty    100000 non-null  int64
 3   reason        100000 non-null  object
 4   date          100000 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [39]:
# Whitespace check:
(inv_move == "").sum()

product_id      0
warehouse_id    0
change_qty      0
reason          0
date            0
dtype: int64

In [40]:
inv_move['reason'].value_counts()

reason
Sale       33538
Restock    33246
Return     33216
Name: count, dtype: int64

### Notes:
- date dtype is wrong.
- Restock: stock comes IN, must be positive. Needs transformation.
- Sale: stock goes OUT, must be negative. Needs transformation.

In [59]:
inv_move['Date'] = pd.to_datetime(inv_move['Date'], errors='coerce')
inv_move.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Product_Id    100000 non-null  object
 1   Warehouse_Id  100000 non-null  object
 2   Change_Qty    100000 non-null  int64
 3   Reason        100000 non-null  object
 4   Date          100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 3.8+ MB

In [61]:
inv_move.head(15)

   Product_Id Warehouse_Id  Change_Qty   Reason       Date
0   PROD00578        WH005         -44  Restock 2024-04-30
1   PROD00704        WH006          82  Restock 2023-01-16
2   PROD00453        WH005           0  Restock 2023-07-20
3   PROD00702        WH007          52     Sale 2023-10-17
4   PROD00119        WH009          47     Sale 2024-10-22
5   PROD00160        WH006          82     Sale 2023-01-19
6   PROD00794        WH009          -3   Return 2023-10-05
7   PROD00299        WH009         -19     Sale 2024-10-30
8   PROD00366        WH008         -27     Sale 2023-12-08
9   PROD00099        WH009          42   Return 2024-07-21
10  PROD00502        WH004          91   Return 2023-11-22
11  PROD00060        WH006         -40   Return 2024-10-30
12  PROD00755        WH005           9   Return 2024-05-31
13  PROD00302        WH009          37   Return 2023-11-11
14  PROD00277        WH006         -49  Restock 2024-09-27

In [60]:
import numpy as np

In [63]:
mask2 = inv_move['Reason'].isin(['Restock', 'Return'])
inv_move['Change_Qty'] = np.where(mask2, inv_move['Change_Qty'].abs(),
                                  -inv_move['Change_Qty'].abs()
                                  )
inv_move.head(15)

   Product_Id Warehouse_Id  Change_Qty   Reason       Date
0   PROD00578        WH005          44  Restock 2024-04-30
1   PROD00704        WH006          82  Restock 2023-01-16
2   PROD00453        WH005           0  Restock 2023-07-20
3   PROD00702        WH007         -52     Sale 2023-10-17
4   PROD00119        WH009         -47     Sale 2024-10-22
5   PROD00160        WH006         -82     Sale 2023-01-19
6   PROD00794        WH009           3   Return 2023-10-05
7   PROD00299        WH009         -19     Sale 2024-10-30
8   PROD00366        WH008         -27     Sale 2023-12-08
9   PROD00099        WH009          42   Return 2024-07-21
10  PROD00502        WH004          91   Return 2023-11-22
11  PROD00060        WH006          40   Return 2024-10-30
12  PROD00755        WH005           9   Return 2024-05-31
13  PROD00302        WH009          37   Return 2023-11-11
14  PROD00277        WH006          49  Restock 2024-09-27

date column converted to date format. change_qty already normalize using rule positive when reason column value is "Restock" or "Return", otherway make it negative.

# Data Cleaning

In [41]:
## standardizing column names

prod.columns = prod.columns.str.strip().str.title()

ord.columns = ord.columns.str.strip().str.title()

cust.columns = cust.columns.str.strip().str.title()

ord_it.columns = ord_it.columns.str.strip().str.title()

inv.columns = inv.columns.str.strip().str.title()

inv_move.columns = inv_move.columns.str.strip().str.title()